apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: insecure-container
  restartPolicy: Always
