apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  namespace: apps
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: secure-container
  restartPolicy: Always
