apiVersion: v1
kind: Pod
metadata:
  name: secure-nginx
  namespace: apps
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: nginx
    image: localhost:5000/my-nginx:latest
  restartPolicy: Never
