apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "simple-kubernetes-webhook.dx.rtx.com"
webhooks:
  - name: "simple-kubernetes-webhook.dx.rtx.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: simple-kubernetes-webhook
        path: /mutate-pods
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVQVJ0c1hUYU04d3RaUHZUb0srb0VTQzRhcitrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERUxNQWtHQTFVRUJoTUNRVlV4R1RBWEJnTlZCQU1NRUhObFkzVnlhWFI1TFhkbFltaHZiMnN3SGhjTgpNakl3TmpJMk1qQXlOekkwV2hjTk1qTXdOakkyTWpBeU56STBXakFvTVFzd0NRWURWUVFHRXdKQlZURVpNQmNHCkExVUVBd3dRYzJWamRYSnBkSGt0ZDJWaWFHOXZhekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBS3ZMUHVnYThoREpMMlFydU5NOXJ3RTZPTkdTckJOaEliNUg3QThqMStRMVNjSVFSbElPTTZqbwp5dUZ1S3hxNy92WGxCZm1GaGV6ZUdPV3E5eERseEp1V0dvUFIxcjROaHBRS09CZHlHN2tGV3pVTXdzanVHNm1OCmltUWFtb0RlSEp3S0dMU2hjeHlTenVwblM5SkV4RlVlSFdsek1BVlA3dXZqb001OXJJVVNJazQyWUFhU3B5eW4KcFFGMEJ0aVkyai83WExhS3NEZkZYSDF4UWlETGNOYk9ZWkhvTDJ5TTBObEhQV1JDa2Y5Qk96T1dFMjVnQjdLWQpWNVpQR2FoWGNSNUZ0L0ZaSmRaMDA3UVR1bjl5MkovL1I5Q09ZS3QxV3BCMG1McnJQbVJUd1lwNWJxYUM3cnlTCm9WQ2p2V2VCYnJvRWxIMHNIbGRVenFkTFNCTnExazhDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkM5UTVjNHQKMGw5Z3V5OVR1RU9LTXpQaXJWTU1NQjhHQTFVZEl3UVlNQmFBRkM5UTVjNHQwbDlndXk5VHVFT0tNelBpclZNTQpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHpnM0dNaWdqZUR5VUgwCitpWndpOHNhaDUxQWZ0d25oNldVTm5iU0owM0FzQzY3S0UrNGtFblJtbkxCS2tQYm1BU1VqMVk3TGc4aGlzU0EKcW9mTFFuKyt4VUU3MGFLZ0ljUEVmMnkwSG5sb1NGTU1iZXJVb0t0cEFFWjBUdHRpRjVMd25NNS84dVdTYnJxRQp3M3ZOdUdRSXk5bTkyUVFYRFZ6OWpHL2JyWHlaY0xramN5M1ZSbW0yRTdpUFJyOHZiTXczeWhTVFUwS2pMYi94CkJ1Uk80TlZmVHNKbmJ2dkdzUGNmUkdGSHd6Y2FkTU43anRkOGJXZzBHekVHL2FFM3RZMEJ6MEV5SXQ3UVBQMDUKQkVkV000ZTdrSHpMUWNhTDJ6OHFMWjRMR1J4ZTBsN1dMdXowVWxOcmROa213WFZDQlFmUUFXSkRYNDl0cm8rTAo1MTB0aC9vPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
